version: '3.3'
services:
  mautic:
    image: mautic/mautic:latest
    links:
      - mauticdb:mysql
    ports:
      - 8080:80
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysecret
      - MAUTIC_DB_NAME=mautic

  mauticdb:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret